// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9iqiqEOnWhp5tHJcWvvo1l0iS_SXHRVI',
    appId: '1:19159557571:web:09cfa605b695643c500976',
    messagingSenderId: '19159557571',
    projectId: 'microcellapp',
    authDomain: 'microcellapp.firebaseapp.com',
    databaseURL: 'https://microcellapp-default-rtdb.firebaseio.com',
    storageBucket: 'microcellapp.firebasestorage.app',
    measurementId: 'G-K3BETE0W1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF9iwDBI7cG7oH7sIyR6WLOhZnBeymIQQ',
    appId: '1:19159557571:android:547f16738408c91f500976',
    messagingSenderId: '19159557571',
    projectId: 'microcellapp',
    databaseURL: 'https://microcellapp-default-rtdb.firebaseio.com',
    storageBucket: 'microcellapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtvEcIocl3AxFGT4eYWVtZt3_rARPFmo',
    appId: '1:19159557571:ios:f0a63cc942cee685500976',
    messagingSenderId: '19159557571',
    projectId: 'microcellapp',
    databaseURL: 'https://microcellapp-default-rtdb.firebaseio.com',
    storageBucket: 'microcellapp.firebasestorage.app',
    iosClientId: '19159557571-h945mtqdaf7m1mnfjg2so8dmetjid2p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.microcellApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKtvEcIocl3AxFGT4eYWVtZt3_rARPFmo',
    appId: '1:19159557571:ios:f0a63cc942cee685500976',
    messagingSenderId: '19159557571',
    projectId: 'microcellapp',
    databaseURL: 'https://microcellapp-default-rtdb.firebaseio.com',
    storageBucket: 'microcellapp.firebasestorage.app',
    iosClientId: '19159557571-h945mtqdaf7m1mnfjg2so8dmetjid2p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.microcellApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9iqiqEOnWhp5tHJcWvvo1l0iS_SXHRVI',
    appId: '1:19159557571:web:e374d4cecee405b1500976',
    messagingSenderId: '19159557571',
    projectId: 'microcellapp',
    authDomain: 'microcellapp.firebaseapp.com',
    databaseURL: 'https://microcellapp-default-rtdb.firebaseio.com',
    storageBucket: 'microcellapp.firebasestorage.app',
    measurementId: 'G-R5EFM01QVH',
  );
}
